document.write('<div id="footer">');
document.write('<table>');
document.write('<tr>');
document.write('<td><a href="/~s2174634/congres/disclaimer.html">Disclaimer</a></td>');
document.write('<td><a href="/~s2174634/congres/linklist.html">Linklist</a></td>');
document.write('<td><a href="/~s2174634/congres/Onderhoudshandboek.pdf" target="_blank">Onderhoudshandboek</a></td>');
document.write('</tr>');
document.write('</table>');
document.write('<copyright>&copy; Mart Busger op Vollenbroek</copyright>');
document.write('</div>');