document.write('<ul><li><a href=\'index.html\'>Home</a></li>');
document.write('<li><a href=\'dice.html\'>Week 1</a></li>');
document.write('<li><a href=\'photobook.html\'>Week 2</a></li>');
document.write('<li><a href=\'quiz.html\'>Week 3</a></li>');
document.write('<li><a href=\'clock.html\'>Week 4</a></li>');
document.write('<li><a href=\'yahtzee.php\'>Week 5</a></li>');
document.write('<li><a href=\'phpquiz.php\'>Week 6</a></li>');
document.write('<li><a href=\'log.html\'>Logboek</a></li>');
document.write('<li><a href=\'congres/main.html\'>Congres site</a></li>');